config/routes.rb
Rails.application.routes.draw do
  root 'user#index'

  resources :user

  get  'login',  to: 'session#new'

  post 'login',  to: 'session#create'
  
  post 'logout', to: 'session#logout'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,     presence: true, length: {maximum: 50}
  validates :password, presence: true, length: {minimum: 6}
  validates :email,    presence: true,
                       format: {with: VALID_EMAIL_REGEX}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      login_user(user)

      redirect_to(user)
    else
      flash[:notice] = "Invalid Email or Password"
      render 'new'
    end
  end

  def logout

    log_out

    flash[:notice] = "User Logged out"

    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User Created! Congratz breh'

      login_user(@user)
      redirect_to root_path
    else
      flash[:notice] = "#{@user.errors.full_messages}"

      render new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login_user(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/session/new.html.erb
<h1>User Login</h1>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= form_for :session, url: {action: :create} do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <br>
  <%= f.submit 'Login User' %>
<% end %>

app/views/user/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<h1> List of users </h1>
<% User.all.each do |u| %>
  <%= "#{u.name}, #{u.email}" %>
  <br>
<% end %>
<br>
<% if current_user.present? %>
  <%= "Current User: #{current_user.name}" %>
  <br>
  <%= link_to "Profile", user_path(current_user) %>
  <%= link_to "Log out", logout_path, method: :post %>
<% else %>
  <%= link_to "Login",  login_path %>
  <%= link_to "Create User", new_user_path %>
<% end %>

app/views/user/new.erb
<h1>Create User</h1>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= form_for @user, url: {action: :create} do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <br>
  <%= f.submit 'Create User' %>
<% end %>

app/views/user/show.html.erb
<h1> User Profile </h1>

<p> User Name: <%= @user.name %></p>
<p> Email: <%= @user.email %></p>

<%= link_to "logout", logout_path, method: :post %>
<%= link_to "Back", root_path %>